default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: easy_peasy_2_app_development

test:
  <<: *default
  database: easy_peasy_2_app_test

production:
  <<: *default
  database: easy_peasy_2_app_production
  username: easy_peasy_2_app
  password: <%= ENV['EASY_PEASY_2_APP_DATABASE_PASSWORD'] %>